### PR TITLE
Switch to GitHub actions + and publish to maven central using sbt-ci-release 

### LINKED ISSUE #1: Publish to Maven central
It seems this library is only hosted on repo.scala-sbt.org which just had a outage: https://github.com/sbt/sbt/issues/7202
I highly recommend publishing a artifacts to maven central via the [sbt-ci-release plugin](https://github.com/sbt/sbt-ci-release) and GitHub actions, see here how this can be done: https://github.com/sbt/sbt-dynver/pull/242

### PR DESCRIPTION
**Pull request by mkurz**
- Fixes #1

@johanandren What you need to do:
1. Add the git tag `0.1` to 58b9cdee3f453be39abfb9a10f05acf8f749bfa0 (because you never did that)
1. Add `SONATYPE_USERNAME`, `SONATYPE_PASSWORD`, `PGP_PASSPHRASE` and `PGP_SECRET` to [this repos "Repository secrets"](https://github.com/johanandren/sbt-akka-version-check/settings/secrets/actions) as described [here](https://github.com/sbt/sbt-ci-release?tab=readme-ov-file#secrets)
1. Merge this pull request
1. Watch how a new snapshot gets published here: https://github.com/johanandren/sbt-akka-version-check/actions/workflows/publish.yml
1. If a snapshot got published successfully you can then try to release the next version to maven central by tagging `0.2`

### CODE REVIEW

**Comment by johanandren** [comment]
Thanks, I think I'd need to change the groupId of this project as well, If I publish it on my own. But I can add that on top of the changes you've shared here before merging.

**Comment by mkurz** [comment]
Thanks @johanandren! Actually Play 2.9 depends on this plugin, so we finally have all our dependencies hosted on maven central :+1:

**Comment by mkurz** [comment]
The switch is fine, I will just upgrade in Play to make use of the new one.

**Comment by johanandren** [comment]
Thanks!

**Pull request merged**
